### ISSUE TITLE
no main manifest attribute, in target/thor-client-sdk4j-0.0.8.jar

### ISSUE THREAD

**Issue by mirei83** [vechain/thor-client-sdk4j#20]
Hey guys, 
I am trying to use the jar file in version 0.0.8. Compiling works without error and there is a file "thor-client-sdk4j-0.0.8.jar" in the folder target. But its only 120KB in size. I already tried this in 0.0.6 and the file was about 23MB. When i try to use the jar file, i get "no main manifest attribute, in target/thor-client-sdk4j-0.0.8.jar".

I tried this in Debian 9 and Ubuntu 19.04.

java -showversion
openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment (build 11.0.3+7-Ubuntu-1ubuntu1)
OpenJDK 64-Bit Server VM (build 11.0.3+7-Ubuntu-1ubuntu1, mixed mode, sharing)

Since I have absolutely no clue about java, I did some googleing and found this: https://www.mkyong.com/maven/how-to-create-a-manifest-file-with-maven/

After adding this to the pom.xml, the manifest error was gone:

<plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <version>2.4</version>
        <configuration>
                <archive>
<manifest>
        <mainClass>com.vechain.thorclient.console.Main</mainClass>
 </manifest>
                </archive>
        </configuration>
</plugin>

But trying to call the chaintag (or any other call) failed with his error:

Exception in thread "main" java.lang.NoClassDefFoundError: com/mashape/unirest/http/exceptions/UnirestException
        at com.vechain.thorclient.console.BlockchainQueryConsole.getChainTag(BlockchainQueryConsole.java:33)
        at com.vechain.thorclient.console.Main.main(Main.java:62)
Caused by: java.lang.ClassNotFoundException: com.mashape.unirest.http.exceptions.UnirestException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)

**Comment by mirei83** [comment]
The XML format got deletet during upload, but you get the idea :D

**Comment by albertma** [comment]
You can read the pom.xml file
or just run the command 
`mvn clean package -Pall  -Dmaven.test.skip=true`

**Comment by mirei83** [comment]
@albertma You are my hero. Thanks a lot for the "-Pall". Generating th jar file this way completely resolved my problem.
